spring:
  profiles:
    active: development
---

spring:
  profiles: development
---

spring:
  profiles: production

zuul:
  ignoredPatterns: /**/swagger-ui.html/**, /swagger-ui.html/**, /**/v2/api-docs/**
---

info:
  component: Edge Server

spring:
  application:
    name: gateway-server

server:
  port: ${PORT:8765}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    hello:
      path: /hello/**
      serviceId: hello-service
    googlesearch:
      path: /googlesearch/**
      serviceId: google-search-service
    wikisearch:
      path: /wikisearch/**
      serviceId: wikipedia-search-service
    localsearch:
      path: /localsearch/**
      serviceId: local-search-service

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/